osx_image: xcode9.3

before_script:
  - carthage update

script:
  - set -o pipefail
  - xcodebuild -workspace Wineskin.xcworkspace -scheme Wineskin build | xcpretty -c
  - xcodebuild -workspace Wineskin.xcworkspace -scheme "Wineskin Winery" build | xcpretty -c
  - xcodebuild -workspace Wineskin.xcworkspace -scheme WineskinLauncher build | xcpretty -c
